### ISSUE TITLE
Not showing up?

### ISSUE THREAD

**Issue by avelk4** [avelk4/ProjectX#1]
@travisdoesmath I don't know what I'm doing wrong...but everytime I try to open the project in my browser nothing is loading?

**Comment by travisdoesmath** [comment]
Hmm. Are you getting any messages/errors in the console in your browser?

Confirming assumptions: are you using Chrome on Windows and visiting https://avelk4.github.io/ProjectX/ ?

**Comment by avelk4** [comment]
@travisdoesmath idk what was happening but that link worked! Also I opened it on my phone and it doesn’t look half bad/usability is actually pretty good!
